[package]
name = "stream_stash_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.16.0"
serde = { version = "1.0.193", features = ["derive"] }
async-std = { version = "1.12.0", features = ["attributes"] }
