name: Build, deploy & run

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Rust
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          CARGO_TERM_COLOR: always
      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: target/release/stream_stash_backend

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: build
      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/stream_stash_backend"
          target: "/var/stream-stash-backend"

  execute:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Execute program
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: "sudo systemctl restart stream-stash-backend"
